# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ea0135387c10bd4a457b92c3fcc276ce6a4358a95bcca87fd5f21bd51c9541e4321ae68f66831c2d7c25d0c1844117c899c057acbdf0bd1692f0b42f846c725

test:
  secret_key_base: b2b0c1e314c1ac0d2da38b8afbc328ca962897bf3e805ccd8d1ec957e248c752a0e574de852c73099b0e0252240ebeaa452fa04296cd1f50275e960e8c9805b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
